filechunk:
    fields:
        ckeditor:
            maxsize: 10000000
            mimetypes: [image/jpeg, image/png]
            naming_strategy: date
            target_directory: public://ckeditor
