
filechunk_remove:
    path: /filechunk/remove
    defaults:
        _controller: MakinaCorpus\FilechunkBundle\Controller\UploadController::remove
    methods: [POST]

filechunk_token:
    path: /filechunk/token
    defaults:
        _controller: MakinaCorpus\FilechunkBundle\Controller\UploadController::token
    methods: [POST]

filechunk_upload:
    path: /filechunk/upload
    defaults:
        _controller: MakinaCorpus\FilechunkBundle\Controller\UploadController::upload
    methods: [POST]
