
filechunk_remove:
    path: /filechunk/remove
    defaults:
        _controller: FilechunkBundle:Upload:remove
    methods: [POST]

filechunk_upload:
    path: /filechunk/upload
    defaults:
        _controller: FilechunkBundle:Upload:upload
    methods: [POST]

#filechunk_test:
#    path: /filechunk/test
#    defaults:
#        _controller: FilechunkBundle:Form:test
