parameters:
    # Warning, the default system temporary folder could differ between
    # CLI and HTTP execution contextes, case in which this will not work,
    # in most projects, you need to set this explicitely.
    filechunk.upload_directory: "%env(resolve:FILE_UPLOAD_DIR)%"
    filechunk.public_directory: "%env(resolve:FILE_PUBLIC_DIR)%"
    filechunk.private_directory: "%env(resolve:FILE_PRIVATE_DIR)%"

services:

    filechunk.command.cleanup_temporary_files:
        public: false
        class: MakinaCorpus\FilechunkBundle\Command\CleanupTemporaryFilesCommand
        calls:
            - [setLogger, ["@logger"]]
            - [setFileSessionHandler, ["@filechunk.session_handler"]]
        tags: [{name: console.command}]

    filechunk_chunked_file_form_type:
        public: false
        class: MakinaCorpus\FilechunkBundle\Form\Type\FilechunkType
        arguments: ["@filechunk.session_handler", "@router"]
        tags: [{name: form.type}]

    filechunk.session_handler:
        public: false
        class: MakinaCorpus\FilechunkBundle\FileSessionHandler
        arguments: ["@filechunk.file_manager", "@session"]

    MakinaCorpus\FilechunkBundle\FileSessionHandler:
        public: true
        alias: filechunk.session_handler

    filechunk.file_manager:
        public: false
        class: MakinaCorpus\FilechunkBundle\FileManager
        arguments: []

    MakinaCorpus\FilechunkBundle\FileManager:
        public: true
        alias: filechunk.file_manager
