parameters:

    env(FILE_PRIVATE_DIR): "%kernel.project_dir%/private"
    env(FILE_PUBLIC_DIR): "%kernel.project_dir%/public/files"
    env(FILE_UPLOAD_DIR): "%kernel.project_dir%/var/tmp/upload"

    filechunk.private_directory: "%env(resolve:FILE_PRIVATE_DIR)%"
    filechunk.public_directory: "%env(resolve:FILE_PUBLIC_DIR)%"
    filechunk.upload_directory: "%env(resolve:FILE_UPLOAD_DIR)%"

services:

    filechunk.command.cleanup_temporary_files:
        public: false
        class: MakinaCorpus\FilechunkBundle\Command\CleanupTemporaryFilesCommand
        calls:
            - [setLogger, ["@logger"]]
            - [setFileSessionHandler, ["@filechunk.session_handler"]]
        tags: [{name: console.command}]

    filechunk_chunked_file_form_type:
        public: false
        class: MakinaCorpus\FilechunkBundle\Form\Type\FilechunkType
        arguments: ["@filechunk.file_manager", "@filechunk.session_handler", "@router"]
        tags: [{name: form.type}]

    filechunk.session_handler:
        public: false
        class: MakinaCorpus\FilechunkBundle\FileSessionHandler
        arguments: ["@filechunk.file_manager", "@session"]

    MakinaCorpus\FilechunkBundle\FileSessionHandler:
        public: true
        alias: filechunk.session_handler

    filechunk.file_manager:
        public: false
        class: MakinaCorpus\FilechunkBundle\FileManager
        arguments:
            $webroot: "%kernel.project_dir%/public"

    MakinaCorpus\FilechunkBundle\FileManager:
        public: true
        alias: filechunk.file_manager
