services:

    MakinaCorpus\FilechunkBundle\Controller\UploadController:
        public: false
        tags: ["controller.service_arguments"]

    filechunk.command.cleanup_temporary_files:
        public: false
        class: MakinaCorpus\FilechunkBundle\Command\CleanupTemporaryFilesCommand
        calls:
            - [setLogger, ["@logger"]]
            - [setFileSessionHandler, ["@filechunk.session_handler"]]
        tags: [{name: console.command}]

    filechunk_chunked_file_form_type:
        public: false
        class: MakinaCorpus\FilechunkBundle\Form\Type\FilechunkType
        arguments: ["@files.file_manager", "@filechunk.session_handler", "@router"]
        tags: [{name: form.type}]

    filechunk.session_handler:
        public: false
        class: MakinaCorpus\FilechunkBundle\FileSessionHandler\RequestStackFileSessionHandler
        arguments: ["@files.file_manager", "@request_stack"]

    MakinaCorpus\FilechunkBundle\FileSessionHandler:
        public: true
        alias: filechunk.session_handler
